In [1]:
!pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

df = pd.read_csv('2025_Airbnb_NYC_listings.csv')

print(df.head())

   Unnamed: 0     id       source  \
0           0  36121  city scrape
1           1  36647  city scrape
2           2  38663  city scrape
3           3  38833  city scrape
4           4  39282  city scrape

                                                name  \
0                 Lg Rm in Historic Prospect Heights
1  1 Bedroom & your own Bathroom, Elevator Apartment
2                   Luxury Brownstone in Boerum Hill
3                 Spectacular West Harlem Garden Apt
4                    “Work-from-home” from OUR home.

                                         description  \
0  Cozy space share in the heart of a great neigh...
1  Private bedroom with your own bathroom in a 2 ...
2  Beautiful, large home in great hipster neighbo...
3  This is a very large and unique  space. An inc...
4  *Monthly Discount will automatically apply <br...

                               neighborhood_overview  host_id host_name  \
0  Full of tree-lined streets and beautiful brown...    62165   Michael
1   Manhattan, SE corner of 2nd Ave/ E. 110th street   157798     Irene
2  diverse, lively, hip, cool: loaded with restau...   165789     Sarah
3  West Harlem is now packed with great restauran...   166532   Matthew
4  THE NEIGHBORHOOD:<br />Our apartment is locate...   168525   Gustavo

   host_since host_location  ... review_scores_communication  \
0  2009-12-11  New York, NY  ...                        5.00
1  2010-07-04  New York, NY  ...                        4.90
2  2010-07-13  New York, NY  ...                        4.88
3  2010-07-14  New York, NY  ...                        4.96
4  2010-07-16  New York, NY  ...                        4.88

  review_scores_location review_scores_value             license  \
0                   5.00                5.00                 NaN
1                   4.38                4.71                 NaN
2                   4.86                4.62  OSE-STRREG-0001784
3                   4.79                4.82  OSE-STRREG-0000476
4                   4.85                4.78  OSE-STRREG-0001150

  instant_bookable calculated_host_listings_count  \
0                f                              1
1                f                              1
2                f                              1
3                f                              1
4                f                              2

   calculated_host_listings_count_entire_homes  \
0                                            0
1                                            0
2                                            0
3                                            1
4                                            0

   calculated_host_listings_count_private_rooms  \
0                                             1
1                                             1
2                                             1
3                                             0
4                                             2

  calculated_host_listings_count_shared_rooms reviews_per_month
0                                           0              0.05
1                                           0              0.58
2                                           0              0.28
3                                           0              1.36
4                                           0              1.54

[5 rows x 73 columns]

In [3]:
df = pd.read_csv('2025_Airbnb_NYC_listings.csv')

print(list(df.columns))
print(f"\n총 컬럼 개수: {len(df.columns)}개")

['Unnamed: 0', 'id', 'source', 'name', 'description', 'neighborhood_overview', 'host_id', 'host_name', 'host_since', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month']

총 컬럼 개수: 73개

In [ ]:
df = pd.read_csv('2025_Airbnb_NYC_listings.csv')

#주요컬럼 : 호스트, 숙소명, 숙소유형, 숙소위치, 가격, 리뷰개수, 평점
selected_cols = [
    'host_name', 'name', 'room_type', 
    'neighbourhood_group_cleansed', 'price', 
    'number_of_reviews', 'review_scores_rating'
]

data = df[selected_cols].copy()

#한글로 컬럼 이름 바꾸기
data.columns = ['호스트', '숙소명', '숙소유형', '위치(구)', '가격', '리뷰수', '평점']

#가격 데이터 숫자형으로 변환
data['가격'] = data['가격'].str.replace('$', '').str.replace(',', '').astype(float)

display(data.head())

,호스트,숙소명,숙소유형,위치(구),가격,리뷰수,평점
0,Michael,Lg Rm in Historic Prospect Heights,Private room,Brooklyn,200.0,9,4.88
1,Irene,"1 Bedroom & your own Bathroom, Elevator Apartment",Private room,Manhattan,82.0,102,4.77
2,Sarah,Luxury Brownstone in Boerum Hill,Private room,Brooklyn,765.0,43,4.70
3,Matthew,Spectacular West Harlem Garden Apt,Entire home/apt,Manhattan,139.0,241,4.85
4,Gustavo,“Work-from-home” from OUR home.,Private room,Brooklyn,130.0,274,4.82

In [27]:
df = pd.read_csv('2025_Airbnb_NYC_listings.csv')

#가격 데이터 숫자형으로 먼저 변환
df['price'] = df['price'].str.replace('$', '').str.replace(',', '').astype(float)

#A: 중요한 컬럼(이름, 호스트명, 가격)이 없는 행은 삭제
df_cleaned = df.dropna(subset=['name', 'price'])

#B: 너무 비어있는 컬럼(예: neighborhood_overview 등)은 컬럼 자체를 삭제 / 데이터의 50% 이상이 비어있는 컬럼 삭제
#df_cleaned = df_cleaned.dropna(thresh=len(df_cleaned)*0.5, axis=1)

#C: 숫자형 데이터 중 남은 결측치는 0으로 채우기
num = df_cleaned.select_dtypes(include=['number']).columns
df_cleaned[num] = df_cleaned[num].fillna(0)

print(f"처음 데이터 개수: {len(df)}")
print(f"결측치 제거 후 데이터 개수: {len(df_cleaned)}")
print(f"남은 컬럼 개수: {len(df_cleaned.columns)}")

#정제 데이터 확인
display(df_cleaned.head())

처음 데이터 개수: 22308
결측치 제거 후 데이터 개수: 22308
남은 컬럼 개수: 73

,Unnamed: 0,id,source,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,36121,city scrape,Lg Rm in Historic Prospect Heights,Cozy space share in the heart of a great neigh...,Full of tree-lined streets and beautiful brown...,62165,Michael,2009-12-11,"New York, NY",...,5.00,5.00,5.00,NaN,f,1,0,1,0,0.05
1,1,36647,city scrape,"1 Bedroom & your own Bathroom, Elevator Apartment",Private bedroom with your own bathroom in a 2 ...,"Manhattan, SE corner of 2nd Ave/ E. 110th street",157798,Irene,2010-07-04,"New York, NY",...,4.90,4.38,4.71,NaN,f,1,0,1,0,0.58
2,2,38663,city scrape,Luxury Brownstone in Boerum Hill,"Beautiful, large home in great hipster neighbo...","diverse, lively, hip, cool: loaded with restau...",165789,Sarah,2010-07-13,"New York, NY",...,4.88,4.86,4.62,OSE-STRREG-0001784,f,1,0,1,0,0.28
3,3,38833,city scrape,Spectacular West Harlem Garden Apt,This is a very large and unique space. An inc...,West Harlem is now packed with great restauran...,166532,Matthew,2010-07-14,"New York, NY",...,4.96,4.79,4.82,OSE-STRREG-0000476,f,1,1,0,0,1.36
4,4,39282,city scrape,“Work-from-home” from OUR home.,*Monthly Discount will automatically apply <br...,THE NEIGHBORHOOD:<br />Our apartment is locate...,168525,Gustavo,2010-07-16,"New York, NY",...,4.88,4.85,4.78,OSE-STRREG-0001150,f,2,0,2,0,1.54

In [25]:
df = pd.read_csv('2025_Airbnb_NYC_listings.csv')

#숫자형 데이터인 컬럼만 골라내기
num_cols = df.select_dtypes(include=['number'])

#결측치(NaN) 개수 계산
na_counts = num_cols.isnull().sum()

#0인 값의 개수 계산
zero = (num_cols == 0).sum()

audit = pd.DataFrame({
    '결측치(NaN) 개수': na_counts,
    '0인 값 개수': zero
})

#값이 0보다 큰 것만
print(audit[ (audit['결측치(NaN) 개수'] > 0) | (audit['0인 값 개수'] > 0) ])

                                              결측치(NaN) 개수  0인 값 개수
Unnamed: 0                                              0        1
host_listings_count                                    20        0
host_total_listings_count                              20        0
bathrooms                                               6      434
bedrooms                                               49     2138
beds                                                   79      635
calendar_updated                                    22308        0
availability_30                                         0     5519
availability_60                                         0     3514
availability_90                                         0     2421
availability_365                                        0      168
number_of_reviews                                       0     6798
number_of_reviews_ltm                                   0    12234
number_of_reviews_l30d                                  0    19400
availability_eoy                                        0      374
number_of_reviews_ly                                    0    12393
estimated_occupancy_l365d                               0    12234
estimated_revenue_l365d                                 0    12234
review_scores_rating                                 6798        0
review_scores_accuracy                               6798        0
review_scores_cleanliness                            6798        0
review_scores_checkin                                6798        0
review_scores_communication                          6798        0
review_scores_location                               6799        0
review_scores_value                                  6798        0
calculated_host_listings_count_entire_homes             0     7181
calculated_host_listings_count_private_rooms            0    11480
calculated_host_listings_count_shared_rooms             0    22089
reviews_per_month                                    6798        0

In [ ]:
#결측치가 왜 발생했는지?
df = pd.read_csv('2025_Airbnb_NYC_listings.csv')

#A : 수치형 데이터 중에서 0이나 결측치가 많은 컬럼 확인
# 리뷰 점수가 없는 숙소가 얼마나 있는지 확인
x_reviews = df['review_scores_rating'].isnull().sum()
print(f"리뷰 점수가 없는 숙소: {x_reviews}개")

#B : '리뷰 점수'가 없는 숙소들은 '리뷰 개수'도 0일까? (도메인 규칙 확인)
no_score = df[df['review_scores_rating'].isnull()]['number_of_reviews'].unique()
print(f"리뷰 점수 없는 숙소들의 리뷰 개수 종류: {no_score}")

#[0] : 점수가 없는 건 리뷰가 쌓이지 않아서

리뷰 점수가 없는 숙소: 6798개
리뷰 점수 없는 숙소들의 리뷰 개수 종류: [0]

In [ ]:
df = pd.read_csv('2025_Airbnb_NYC_listings.csv')

print(df['minimum_nights'].describe())

count    22308.000000
mean        27.249417
std         32.428943
min          1.000000
25%         30.000000
50%         30.000000
75%         30.000000
max        730.000000
Name: minimum_nights, dtype: float64

뉴욕주 다세대 주택법 : 아파트 같은 다세대 주택(3세대 이상 거주 빌딩)의 경우, 집주인(호스트)이 함께 거주하지 않으면서 30일 미만으로 집 전체를 대여하는 것을 불법으로 규정함

그래서 많은 호스트가 실제로는 짧게 빌려도 데이터상에는 '30박'이라고 기입함

In [20]:
df = pd.read_csv('2025_Airbnb_NYC_listings.csv')

#30박 이상으로 설정된 숙소는 전체의 몇 %?
long_term = (df['minimum_nights'] >= 30).mean() * 100
print(f"\n최소 숙박일이 30박 이상인 숙소 비중: {long_term :.2f}%")

최소 숙박일이 30박 이상인 숙소 비중: 80.43%

30일 이상인 숙소가 80% 이상
이 데이터 분석으로 알 수 있는 인사이트 : 뉴욕 에어비앤비 시장이 '단기 여행자'를 위한 곳이 아니라 '중장기 체류자' 위주로 완전히 재편됐다.

어쩌면 80%의 호스트가 법(뉴욕주 다세대 주택법) 때문에 '30박'이라는 거짓말을 치고 있을 수도 있음